### ISSUE TITLE
Fails to Build Due to Undefined Symbol Errors

### ISSUE THREAD

**Issue by 266-750Balloons** [Malcohol/Fickle-C64#1]
I am on Debian Testing (Bookworm), Kernel version 5.16 on x86_64. As far as I can tell, I have dependencies filled. After running make, I get the following output:
```
ca65 --cpu 6502X -g main.s
main.s(2709): Error: Symbol 'LUT_LINE_TABLE_HI' is undefined
main.s(2719): Note: Expanded from here
main.s(2707): Error: Symbol 'LUT_LINE_TABLE_LO' is undefined
main.s(2717): Note: Expanded from here
main.s(2098): Error: Symbol 'LUT_INTERRUPT_RASTER_TABLE' is undefined
main.s(220): Error: Symbol 'BOTTOM_OF_SCREEN_RASTER' is undefined
main.s(324): Note: Expanded from here
main.s(338): Note: Expanded from here
main.s(350): Note: Expanded from here
tables.s(232): Error: Symbol 'LUT_INTERRUPT_ROUTINES' is undefined
main.s(165): Note: Expanded from here
main.s(167): Note: Expanded from here
main.s(169): Note: Expanded from here
main.s(171): Note: Expanded from here
main.s(350): Note: Expanded from here
tables.s(232): Error: Symbol 'LUT_INTERRUPT_ROUTINES_END' is undefined
main.s(165): Note: Expanded from here
main.s(167): Note: Expanded from here
make: *** [Makefile:26: main.o] Error 1
```

**Comment by Malcohol** [comment]
Thanks for the information. Yep. I'm reproducing approximately the same in Ubuntu:

```
ca65 --cpu 6502X -g main.s
main.s(2098): Error: Symbol `LUT_INTERRUPT_RASTER_TABLE' is undefined
main.s(220): Error: Symbol `BOTTOM_OF_SCREEN_RASTER' is undefined
tables.s(232): Error: Symbol `LUT_INTERRUPT_ROUTINES' is undefined
tables.s(232): Error: Symbol `LUT_INTERRUPT_ROUTINES_END' is undefined
make: *** [Makefile:26: main.o] Error 1
```

**Comment by Malcohol** [comment]
Hmmm. I use two python scripts to generate some tricksy code, and it seems that sometimes the scripts don't produce output. In my case, it was the buildInterruptTable.py script, and in your case, it looks like neither script did. It seems to be very intermittent, but the makefile doesn't try to rerun the scripts once it sees the file they created, even if they are empty. You can use these two commands to force the generation:
```
python buildLineTable.py > lineTable.s
python buildInterruptTables.py > interruptTables.s
```
Unfortunately, after I did this the build is always successful, I can no longer reproduce the issue (even if I completely clean my git repo) :O

Note: If you get "../exomizer/exomizer2/src/exomizer: not found" after the above fix, it just means you need to go into that folder and build it using "make".

Sorry for the hassle. If I'm able to reproduce the issue again, I'll try to understand it better.

Malcolm

**Comment by Malcohol** [comment]
@266-750Balloons Can I ask if you installed Python27 just before trying to build Fickle? (I did, and if there was a one-time post-install glitch, it could maybe explain why I can't reproduce the issue.)

**Comment by 266-750Balloons** [comment]
I never installed Python 2.7. That would explain some of the issues. I managed to simply edit the print commands, and the script ran fine under Python3, and I was able to successfully build and start it up in VICE. Thanks for your help. Should I make a pull request with the Python3 versions of the script?

**Comment by Malcohol** [comment]
That'd be great, thanks!
